### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by cordoval**
idea is for .git/info/exclude not here

you should ignore the lock of your app

### CODE REVIEW

**Comment by erikaheidi** [comment]
For applications, the composer.lock file must be kept in the repository. See http://stackoverflow.com/questions/12896780/composer-lock-part-of-the-repository

**Comment by cordoval** [comment]
it depends see https://github.com/symfony/symfony-standard

**Comment by henrikbjorn** [comment]
@cordoval symfony-standard is not a application in the same sense, it is a skeleton and therefor it want to install the last minor versions from composer.json when i composer install is runned the first time. Also the lock file is not ignored in symfony-standard.

**Comment by cordoval** [comment]
@henrikbjorn i have ran into some cases where the composer bears a dependency that is specific to a system.
The lock file then forces the user to ran impossible dependencies and alter their system unnecessarily. One of this cases is the intl extension on ubuntu and gives errors coming from the dependency of symony/icu which in fact the
problem is to have an old version of the extension. :baby:

**Comment by henrikbjorn** [comment]
That is not a composer problem but a problem of using the ext or icu packages.

**Pull request closed without merging**
